ledger: extract Wasm state from UTXO snapshots (#239)
Rather than uploading the whole Wasm snapshot as part of the
transaction, extract the snapshot state and store that in the
transaction instead.

Also added some ledger CLI getter subcommands

I had to switch the runtime to do string lookups at call time, since the
contract's compiled component might not correspond to the UTXO's
compiled component

The ledger now serves UTXO methods over wRPC at `starstream:ledger/utxo`

```shell
$ ./starstream wasm -c ./examples/require_hash_preimage.star --output-component hash.wasm
$ starstream-ledger-cli digest ./hash.wasm 
bciqknicpvzese3thpr4c7tmpsyk7qgnlhwoaoxpvj5dtsgmfclxjbqa
$ cat genesis.toml
[[scripts]]
contract = "bciqknicpvzese3thpr4c7tmpsyk7qgnlhwoaoxpvj5dtsgmfclxjbqa"
script = "create-hash"
args = ["42"]
```

```shell
$ cargo run --bin starstream-ledger-node -- --genesis genesis.toml --import hash.wasm
```

```shell
$ starstream-ledger-cli contract script call --simulate --import ./hash.wasm --output-transaction tx.cbor bciqknicpvzese3thpr4c7tmpsyk7qgnlhwoaoxpvj5dtsgmfclxjbqa consume-hash :0 41
Error: failed to call function

Caused by:
    0: failed to call function
    1: error while executing at wasm backtrace:
           0:    0x7f6 - <unknown>!<wasm function 16>
           1:    0x86d - <unknown>!<wasm function 21>
           2:    0x876 - <unknown>!<wasm function 22>
    2: wasm trap: wasm `unreachable` instruction executed
1 $ starstream-ledger-cli contract script call --simulate --import ./hash.wasm --output-transaction tx.cbor bciqknicpvzese3thpr4c7tmpsyk7qgnlhwoaoxpvj5dtsgmfclxjbqa consume-hash :0 42
()
$ starstream-ledger-cli transaction show tx.cbor  
context = "starstream:transaction"
network = "dev"

[payload]
outputs = []
events = []
proof = ""

[[payload.inputs]]
transaction = ""
index = 1
$ printf admin | sha256sum | cut -d' ' -f1 > admin.key
$ starstream-ledger-cli contract script call --key admin.key --import ./hash.wasm bciqknicpvzese3thpr4c7tmpsyk7qgnlhwoaoxpvj5dtsgmfclxjbqa consume-hash :0 42
()
$ starstream-ledger-cli contract script call --key admin.key --import ./hash.wasm bciqknicpvzese3thpr4c7tmpsyk7qgnlhwoaoxpvj5dtsgmfclxjbqa consume-hash :0 42
Error: input not found
```

---------

Signed-off-by: Roman Volosatovs <rvolosatovs@riseup.net>